ec/urls.py
from django.urls import path
from ec import views

urlpatterns = [
    path('item/', views.ItemListView.as_view(), name='item_list'),
    path('item/<slug>', views.ItemDetailView.as_view(), name='item_detail'),
    path('additem/<slug>', views.addItem, name='additem'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('removeitem/<slug>', views.removeItem, name='removeitem'),
    path('removesingleitem/<slug>', views.removeSingleItem, name='removesingleitem'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('ec/', include('ec.urls')),
    path('appointment/', include('appointment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from accounts.models import CustomUser
from django.utils import timezone
from django.urls import reverse

class Gender(models.Model):
    name = models.CharField('性別', max_length=5)

    def __str__(self):
        return self.name

class User(models.Model):
    account_core = models.OneToOneField(CustomUser, verbose_name='アカウント', on_delete=models.CASCADE)
    name = models.CharField('名前', max_length=50)
    furigana = models.CharField(('フリガナ'), max_length=50, null=True, blank=True)
    gender = models.ForeignKey(Gender, verbose_name='性別', on_delete=models.CASCADE, null=True, blank=True)
    tel = models.CharField('電話番号', max_length=100, null=True, blank=True)
    address = models.CharField(('住所'), max_length=100, null=True, blank=True)
    description = models.TextField('備考欄', default="", blank=True)
    created = models.DateTimeField(('来店日'), default=timezone.now)

    def __str__(self):
        return f'{self.furigana} ＋ {self.account_core.email}'

class Staff(models.Model):
    account_core = models.OneToOneField(CustomUser, verbose_name='アカウント', on_delete=models.CASCADE)
    name = models.CharField('名前', max_length=50)
    furigana = models.CharField(('フリガナ'), max_length=50, null=True, blank=True)
    gender = models.ForeignKey(Gender, verbose_name='性別', on_delete=models.CASCADE, null=True, blank=True)
    position = models.CharField(('役職'), max_length=30, blank=True)
    description = models.TextField('自己紹介', default="", blank=True)
    image = models.ImageField(upload_to='images', verbose_name='プロフィール画像', null=True, blank=True)
    tel = models.CharField('電話番号', max_length=100, null=True, blank=True)
    address = models.CharField(('住所'), max_length=100, null=True, blank=True)
    created = models.DateTimeField(('勤務開始日'), default=timezone.now)

    def __str__(self):
        return f'{self.furigana} ＋ {self.account_core.email}'

# サロン
class Salon(models.Model):
    name = models.CharField('サロン名', max_length=30, null=True, blank=True)
    sub = models.CharField('サブタイトル', max_length=50, null=True, blank=True)
    concept1 = models.TextField('コンセプト１', default="", blank=True)
    concept2 = models.TextField('コンセプト2', default="", blank=True)
    mail = models.CharField('メールアドレス', max_length=200, null=True, blank=True)
    tel = models.CharField('電話番号', max_length=200, null=True, blank=True)
    opening = models.CharField('開店時間', max_length=30, null=True, blank=True)
    closed = models.CharField('閉店時間', max_length=30, null=True, blank=True)
    regular_holiday = models.CharField(('定休日'), max_length=100, null=True, blank=True)
    address = models.CharField(('住所'), max_length=100, null=True, blank=True)
    access = models.TextField('アクセス', default="", blank=True)
    twitter = models.CharField('twitter', max_length=100, null=True, blank=True)
    instagram = models.CharField('instagram', max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

# News
class News(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='images', verbose_name='画像', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('news_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title


# Style
class StyleCategory(models.Model):
    name = models.CharField('カテゴリ', max_length=50)

    def __str__(self):
        return self.name

class Style(models.Model):
    category = models.ForeignKey(StyleCategory, verbose_name='スタイルカテゴリ', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    detail = models.TextField()
    stylist = models.ForeignKey(Staff, verbose_name='スタイリスト', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images', verbose_name='画像', null=True, blank=True)

    def __str__(self):
        return self.name


# メニュー
class MenuCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Menu(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    category = models.ForeignKey(MenuCategory, verbose_name='メニュカテゴリー', on_delete=models.CASCADE)
    description = models.TextField(default="", blank=True)
    time = models.IntegerField()

    def __str__(self):
        return self.title

appointment/models.py
from django.conf import settings
from django.db import models
from app.models import User, Staff
from django.utils import timezone
from accounts.models import CustomUser

class Stylist(models.Model):
    detail = models.OneToOneField(Staff, verbose_name='スタイリスト', on_delete=models.CASCADE)

    def __str__(self):
        return self.detail.name

class Booking(models.Model):
    staff = models.ForeignKey(Staff, verbose_name='スタイリスト', on_delete=models.CASCADE)
    name = models.CharField('名前', max_length=50, null=True, blank=True)
    furigana = models.CharField('フリガナ', max_length=50, null=True, blank=True)
    tel = models.CharField('電話番号', max_length=30, null=True, blank=True)
    remarks = models.TextField('備考', default="ご要望などをお書きください", blank=True)
    start = models.DateTimeField('開始時間', default=timezone.now)
    end = models.DateTimeField('終了時間', default=timezone.now)

    def __str__(self):
        start = timezone.localtime(self.start).strftime('%Y/%m/%d %H:%M')
        end = timezone.localtime(self.end).strftime('%Y/%m/%d %H:%M')
        return f'{self.name} {start} ~ {end} {self.staff}'

app/templates/app/about.html
{% extends "app/base.html" %}
{% load static %}
{% block content %}
<div class="main-wrap">
    <div class="container">
        <div class="row">
            <!-- About -->
            <!-- タイトル -->
            <div class="col-12 my-4 px-0">
                <h2 class="text-center">ABOUT</h2>
                <!-- 画像 -->
                <div class="">
                    <img class="img-fluid page-top-img" src="{% static 'img/top_img.jpg' %}" alt="">
                </div>
            </div>

            <div class="content-wrap">
                <!-- コンセプト -->
                <div class="col-12 my-4 px-0">
                    <div class="row">
                        <!-- ロゴ -->
                        <div class="col-3">
                            <h3>Design</h3>
                            <p>{{ salon_data.sub|linebreaksbr }}</p>
                        </div>
                    </div>

                    <!-- コンセプト1 -->
                    <div class="row">
                        <!-- 写真 -->
                        <div class="col-12 col-md-6 px-0">
                            <img class="img-fluid" src="{% static 'img/top_img.jpg' %}" alt="">
                        </div>
                        <!-- コンセプト紹介 -->
                        <div class="col-12 col-md-6 border p-0">
                            <div class="top-about my-5">
                                <div class="text-center">
                                    <p>{{ salon_data.concept1|linebreaksbr }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- コンセプト2 -->
                    <div class="row">
                        <!-- コンセプト紹介 -->
                        <div class="col-12 col-md-6 border">
                            <div class="top-about my-5">
                                <div class="text-center">
                                    <p>{{ salon_data.concept2|linebreaksbr }}</p>
                                </div>
                            </div>
                        </div>
                        <!-- 写真 -->
                        <div class="col-12 col-md-6 px-0">
                            <img class="img-fluid" src="{% static 'img/top_img.jpg' %}" alt="">
                        </div>
                    </div>
                </div>

                <!-- アクセス情報 -->
                <div class="col-12 my-5 px-0">
                    <div class="border">
                        <h3 class="text-center my-3">ACCESS</h3>
                        <div class="row p-3">
                            <div class="col-6">
                                <!-- 店舗情報 -->
                                <h4>Design</h4>
                                <p class="border-bottom">住所：{{ salon_data.address }}</p>
                                <p class="border-bottom">Tel：{{ salon_data.tel }}</p>
                                <p class="border-bottom">Mail：{{ salon_data.mail }}</p>
                                <p class="border-bottom">営業時間：{{ salon_data.opening }}〜{{ salon_data.closed }}</p>
                                <p class="border-bottom">定休日：{{ salon_data.regular_holiday }}</p>
                                <p class="border-bottom">最寄駅：{{ salon_data.access }}</p>
                            </div>
                            <div class="col-6">
                                <div class="border text-center px-0">
                                    <iframe
                                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.486897005143!2d139.68991201492724!3d35.689634180192286!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188cd4b71a37a1%3A0xf1665c37f38661e8!2z5p2x5Lqs6YO95bqB!5e0!3m2!1sja!2sjp!4v1602416303473!5m2!1sja!2sjp"
                                        width="100%" height="100%" frameborder="0" style="border:0;" allowfullscreen=""
                                        aria-hidden="false" tabindex="0"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
        integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous" />
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>美容院予約サイト</title>
</head>

<body>
    <div class="nav-bar">
        <div class="side-bar">
            <div class="side-logo">
                <a class="" href="/">
                    <h2 class="m-0">Design</h2>
                </a>
            </div>
            <div class="side-menu">
                <div>
                    <ul class="navbar-nav nav-menu">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Top</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'news_list' %}">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'menu' %}">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'stylist_list' %}">Stylist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'style_list' %}">Style</a>
                        </li>
                        {% if user.is_authenticated %} 
                            {% if user.is_superuser %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_staff_signup' %}">Signup(Staff)</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'profile' %}">Mypage</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'stylist_choice' %}">Appoint</a>
                            </li>
                            {% if user.account_type == 1 %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'item_list' %}">Shop</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'order' %}">Cart</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link nav-link-end" href="{% url 'account_logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                        </li>
                    </ul>
                </div>
                <div class="side-icon">
                    <a href="https://www.instagram.com/explore/tags/%E7%BE%8E%E5%AE%B9%E5%AE%A4/?hl=ja">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="https://twitter.com/hashtag/%E7%BE%8E%E5%AE%B9%E5%AE%A4">
                        <i class="fab fa-twitter"></i>
                    </a>
                </div>
                <div class="side-info">
                    <span><i class="fas fa-phone-volume"></i> xxx-xxxx-xxxx</span>
                    <p style="font-size: 0.5rem">
                        営業時間：10:00〜20:00<br />定休日：火曜日
                    </p>
                </div>
            </div>
        </div>
    </div>

    <main>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-2 bg-dark mt-5">
            <p class="m-0 text-center text-white">Copyright &copy; Hair-salon 2020</p>
        </footer>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>

    {% block extra_js %} {% endblock %}
</body>

</html>

app/templates/app/contact_thanks.html
{% extends "app/base.html" %}
{% load static %}
{% block content %}
<div class="main-wrap">
    <div class="container">
        <div class="row">
            <!-- Contact Thanks -->
            <!-- タイトル -->
            <div class="col-12 my-4 px-0">
                <h2 class="text-center">Thanks!</h2>
            </div>

            <div class="text-center my-5">
                <h1 class="mb-5">お問い合わせありがとうございました。</h1>
                <p class="mb-2">内容を確認し次第、ご連絡させて頂きます。</p>
                <p class="mb-4">しばらくお待ちくださいませ。</p>
                <a class="btn btn-warning" href="/">ホームに戻る</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}
<div class="main-wrap">
    <div class="container">
        <div class="row">
            <!-- カルーセル -->
            <div class="carousel slide px-0" data-ride="carousel" id="top-carousel">
                <ol class="carousel-indicators">
                    <li data-target="#top-carousel" data-slide-to="0"></li>
                    <li data-target="#top-carousel" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="img-cover" src="{% static 'img/top_img.jpg' %}" alt="First-slide">
                    </div>
                    <div class="carousel-item">
                        <img class="img-cover" src="{% static 'img/top_img2.jpg' %}" alt="Second-slide">
                    </div>
                </div>
            </div>

            <div class="content-wrap">
                <!-- About -->
                <div class="col-12 my-5 px-0">
                    <h5 class="text-center">ABOUT</h5>
                    <div class="row top-concept">
                        <!-- 写真 -->
                        <div class="col-12 col-md-6 px-0 mx-0">
                            <img class="img-fluid" src="{% static 'img/top_img.jpg' %}" alt="">
                        </div>
                        <!-- コンセプト紹介 -->
                        <div class="col-12 col-md-6 border pl-0">
                            <div class="top-about my-5">
                                <div class="text-center">
                                    <p>あなたにあったヘアスタイルをご提案します。</p>
                                    <a href="{% url 'about' %}" class="btn btn-outline-dark">
                                        <span>more</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- News -->
                <div class="col-12 mb-5 px-0">
                    <h5 class="text-center">NEWS</h5>
                    <div class="border border-secondary p-3">
                        {% for news in news_data %}
                        <ul>
                            <li>
                                <a href="{% url 'news_detail' news.id %}">
                                    <p>{{ news.created_date|date:"Y/m/d f" }}：{{ news.title }}</p>
                                </a>
                            </li>
                        </ul>
                        {% empty %}
                        <p>投稿がありません</p>
                        {% endfor %}
                    </div>
                </div>

                <!-- スタイリスト -->
                <div class="col-12 mb-5 px-0">
                    <div class="border border-secondary">
                        <div class="row">
                            <div class="col-12 px-0">
                                <div class="row">
                                    <div class="col-3 center px-0">
                                        <div class="">
                                            <h5 class="">STYLISTS</h5>
                                        </div>
                                    </div>
                                    {% for stylist in staff_data|slice:":3" %}
                                    <div class="col-3 px-0">
                                        {% if stylist.image %}
                                        <a href="{% url 'stylist_detail' stylist.pk  %}" class="">
                                            <img src="{{ stylist.image.url }}" alt="" class="top-stylist-img">
                                        </a>
                                        {% endif %}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 text-right">
                        <button class="btn btn-outline-secondary">
                            <a href="{% url 'stylist_list' %}">スタイリスト一覧を見る</a>
                        </button>
                    </div>
                </div>

                <!-- スタイル -->
                <div class="col-12 mb-5 px-0">
                    <div class="border border-secondary">
                        <div class="row">
                            <div class="col-12 px-0">
                                <div class="row">
                                    <div class="col-2 center px-0">
                                        <h5 class="text-center">STYLE</h5>
                                    </div>
                                    {% for style in style_data|slice:":5" %}
                                    <div class="col-2 px-0">
                                        {% if style.image %}
                                        <a href="{% url 'style_detail' style.pk  %}" class="">
                                            <img src="{{ style.image.url }}" alt="" class="top-stylist-img">
                                        </a>
                                        {% endif %}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 text-right">
                        <button class="btn btn-outline-secondary">
                            <a href="{% url 'style_list' %}">スタイルカタログを見る</a>
                        </button>
                    </div>
                </div>

                <!-- Shop -->
                <div class="col-12 my-5 px-0">
                    <h5 class="text-center">SHOP</h5>
                    <div class="row top-concept">
                        <!-- 写真 -->
                        <div class="col-12 col-md-6 px-0">
                            <img class="img-fluid" src="{% static 'img/shampoo.jpg' %}" alt="">
                        </div>
                        <!-- Shop紹介 -->
                        <div class="col-12 col-md-6 border px-0">
                            <div class="top-about my-5">
                                <div class="text-center">
                                    <p>当サロンで好評販売中の商品を取り揃えております。</p>
                                    <a href="{% url 'item_list' %}" class="btn btn-outline-dark">
                                        <span>To Our Shop</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

app/templates/app/style_detail.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<div class="main-wrap">
    <div class="container">
        <div class="row">
            <!-- スタイル詳細 -->
            <!-- タイトル -->
            <div class="col-12 my-4 px-0">
                <h2 class="text-center">STYLE</h2>
            </div>

            <div class="content-wrap">
                <div class="col-12 my-4">
                    <!-- ---------- スタイル詳細 ---------- -->
                    <div class="row">
                        <!-- スタイリスト画像 -->
                        <div class="col-12">
                            <div class="">
                                {% if style_data.image %}
                                <img class="img-fluid" src="{{ style_data.image.url }}" alt="">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="row border p-3">
                                <div class="col-5">
                                    <img class="img-fluid round-img" src="{{ style_data.stylist.image.url }}" alt="">
                                </div>
                                <div class="col-7 d-flex align-items-center">
                                    <h3>Stylist：{{ style_data.stylist.name }}<br>
                                        Style：{{ style_data.category }}</h3>
                                </div>
                                <hr class="my-3">
                                <h5>スタイル</h5>
                                <p>{{ style_data.name }}</p>
                                <h5 class="mt-3">メニュー・こだわり</h5>
                                <p>{{ style_data.detail|linebreaksbr }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="col-12">
                    <div class="text-center">
                        <div class="btn btn-dark">
                            <a href="{% url 'style_list' %}" class="d-block">
                                <span class="text-white">BACK</span>
                            </a>
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/app/stylist_detail.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<div class="main-wrap">
    <div class="container">
        <div class="row">
            <!-- スタイリスト詳細 -->
            <!-- タイトル -->
            <div class="col-12 my-4">
                <h2 class="text-center">STYLIST</h2>
            </div>

            <div class="content-wrap">
                <div class="col-12 my-4">
                    <!-- ---------- スタイリスト詳細 ---------- -->
                    <div class="row">
                        <!-- スタイリスト画像 -->
                        <div class="col-5">
                            <div class="d-flex justify-content-center">
                                <img class="img-fluid"
                                    src="{{ staff_data.image.url }}" alt="">
                            </div>
                        </div>
                        <div class="col-7">
                            <div class="border p-2">
                                <h5>{{ staff_data.position }}</h5>
                                <h2>{{ staff_data.name }}</h2>
                                <hr>
                                <h5>PROFILE</h5>
                                <p>{{ staff_data.description|linebreaksbr }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>

                <!-- カレンダー -->
                <div class="col-12 my-4">
                    <div class="text-center mb-3">
                        <h4>スタイリストの出勤・予約情報</h4>
                    </div>
                    <!-- 週の切り替え -->
                    <div class="d-flex mb-2">
                        <div class="mx-3 mr-auto">
                            <a class="btn btn-warning" href="">前週</a>
                        </div>
                        <div class="mx-3">
                            <a class="btn btn-warning" href="">次週</a>
                        </div>
                    </div>
                    <!-- カレンダー -->
                    <div class="">
                        <table class="table table-bordered bg-light text-center">
                            <thead class="thead-light">
                                <tr>
                                    <th></th>
                                    {% for day in days %}
                                    <!-- 土曜日 -->
                                    {% if day.weekday == 5 %}
                                    <th scope="col" class="text-primary">{{ day | date:"d(D)" }}</th>
                                    <!-- 日曜日 -->
                                    {% elif day.weekday == 6 %}
                                    <th scope="col" class="text-danger">{{ day | date:"d(D)" }}</th>
                                    {% else %}
                                    <th scope="col">{{ day | date:"d(D)" }}</th>
                                    {% endif %}
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody>
                                {% for hour, schedules in calendar.items %}
                                <tr>
                                    <td scope="row">{{ hour }}:00</td>
                                    {% for datetime, book in schedules.items %}
                                    <td>
                                        {% if datetime <= today %}
                                        -
                                        {% elif book %}
                                        <i class="far fa-circle text-info"></i>
                                        {% else %}
                                        <i class="fas fa-times text-danger"></i>
                                        {% endif %}
                                    </td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="col-12">
                    <div class="text-center">
                        <div class="btn btn-dark">
                            <a href="{% url 'stylist_list' %}" class="d-block">
                                <span class="text-white">BACK</span>
                            </a>
                        </div>
                        <!-- <div class="btn btn-outline-dark">
                            <a href="{% url 'stylist_choice' %}" class="d-block">
                                <span>APPOINT</span>
                            </a>
                        </div> -->
                    </div>
                </div>
            </div>

        </div>
    </div>
    {% endblock content %}